"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { addDays, addMonths, addWeeks, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, parseISO, startOfMonth, startOfWeek, subMonths } from "date-fns";
import { Archive, CalendarDays, ChevronLeft, ChevronRight, Clock3, LayoutDashboard, Plus, Search, Settings, Trash2, Upload, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import "./pro.css";

type View="overview"|"calendar"|"customers"|"services"|"settings";
type Appointment={id:number;customerName:string;customerEmail:string;customerPhone:string;service:string;staffName:string;appointmentDate:string;startTime:string;durationMins:number;status:string;notes:string;price:number};
type Service={id:number;name:string;duration:number;price:number;description:string};
const seed:Appointment[]=[
{id:1,customerName:"Maya Chen",customerEmail:"maya@example.com",customerPhone:"+359 88 410 2281",service:"Consultation",staffName:"Dimitar",appointmentDate:"2026-09-01",startTime:"09:30",durationMins:60,status:"confirmed",notes:"First consultation",price:75},
{id:2,customerName:"Daniel Reed",customerEmail:"daniel@example.com",customerPhone:"+359 88 512 4430",service:"Follow-up",staffName:"Dimitar",appointmentDate:"2026-09-02",startTime:"10:30",durationMins:45,status:"confirmed",notes:"Review progress",price:45},
{id:3,customerName:"Sofia Patel",customerEmail:"sofia@example.com",customerPhone:"+359 88 622 8190",service:"Strategy session",staffName:"Elena",appointmentDate:"2026-09-04",startTime:"10:00",durationMins:90,status:"confirmed",notes:"Quarterly planning",price:120},
{id:4,customerName:"Lucas Martin",customerEmail:"lucas@example.com",customerPhone:"+359 88 701 9921",service:"Quick check-in",staffName:"Dimitar",appointmentDate:"2026-09-01",startTime:"12:00",durationMins:30,status:"completed",notes:"",price:30},
{id:5,customerName:"Amelia Stone",customerEmail:"amelia@example.com",customerPhone:"+359 88 392 0074",service:"Consultation",staffName:"Elena",appointmentDate:"2026-09-03",startTime:"13:00",durationMins:60,status:"confirmed",notes:"",price:75},
{id:6,customerName:"Noah Wilson",customerEmail:"noah@example.com",customerPhone:"+359 88 833 2501",service:"Follow-up",staffName:"Dimitar",appointmentDate:"2026-09-05",startTime:"12:30",durationMins:45,status:"confirmed",notes:"",price:45},
{id:7,customerName:"Eva Brooks",customerEmail:"eva@example.com",customerPhone:"+359 88 412 8070",service:"Consultation",staffName:"Elena",appointmentDate:"2026-09-09",startTime:"11:00",durationMins:60,status:"confirmed",notes:"Product planning",price:75},
{id:8,customerName:"Nikolai Ivanov",customerEmail:"nikolai@example.com",customerPhone:"+359 88 945 6112",service:"Strategy session",staffName:"Dimitar",appointmentDate:"2026-09-11",startTime:"14:00",durationMins:90,status:"confirmed",notes:"",price:120}];
const defaultServices:Service[]=[{id:1,name:"Consultation",duration:60,price:75,description:"Understand the problem and define the next step."},{id:2,name:"Follow-up",duration:45,price:45,description:"Review progress and remove new blockers."},{id:3,name:"Strategy session",duration:90,price:120,description:"A deeper workshop for complex workflows."},{id:4,name:"Quick check-in",duration:30,price:30,description:"Short updates and focused decisions."}];
const DAILY_LIMIT=6;

export default function BookingBoardPro(){
 const [view,setView]=useState<View>("overview"),[appointments,setAppointments]=useState(seed),[services,setServices]=useState(defaultServices),[archived,setArchived]=useState<string[]>([]),[weekStart,setWeekStart]=useState(startOfWeek(new Date(2026,8,2),{weekStartsOn:1})),[month,setMonth]=useState(new Date(2026,8,1)),[bookingOpen,setBookingOpen]=useState(false),[editing,setEditing]=useState<Appointment|null>(null),[selected,setSelected]=useState<Appointment|null>(null),[serviceOpen,setServiceOpen]=useState(false),[query,setQuery]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{fetch("/api/appointments").then(r=>r.ok?r.json():null).then(d=>d?.appointments?.length&&setAppointments(d.appointments)).catch(()=>{});fetch("/api/services").then(r=>r.ok?r.json():null).then(d=>d?.services?.length&&setServices(d.services)).catch(()=>{});fetch("/api/customers").then(r=>r.ok?r.json():null).then(d=>d?.archived&&setArchived(d.archived)).catch(()=>{});},[]);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(weekStart,i)),[weekStart]);
 const visible=appointments.filter(a=>`${a.customerName} ${a.customerEmail} ${a.service} ${a.staffName}`.toLowerCase().includes(query.toLowerCase()));
 const weekAppointments=visible.filter(a=>days.some(d=>isSameDay(parseISO(a.appointmentDate),d)));
 const customers=useMemo(()=>Array.from(new Map(appointments.map(a=>[a.customerEmail,a])).values()).filter(a=>`${a.customerName} ${a.customerEmail}`.toLowerCase().includes(query.toLowerCase())),[appointments,query]);
 const flash=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(""),3000)};
 async function saveBooking(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),v=(n:string)=>String(f.get(n)??"");const item:Appointment={id:editing?.id??Date.now(),customerName:v("customerName"),customerEmail:v("customerEmail"),customerPhone:v("customerPhone"),service:v("service"),staffName:v("staffName"),appointmentDate:v("appointmentDate"),startTime:v("startTime"),durationMins:Number(v("durationMins")),status:editing?.status??"confirmed",notes:v("notes"),price:Number(v("price"))};const st=mins(item.startTime),en=st+item.durationMins,conflict=appointments.some(a=>a.id!==item.id&&a.status!=="cancelled"&&a.staffName===item.staffName&&a.appointmentDate===item.appointmentDate&&st<mins(a.startTime)+a.durationMins&&en>mins(a.startTime));if(conflict){flash(`${item.staffName} already has a booking at that time.`);return}const method=editing?"PATCH":"POST";const response=await fetch("/api/appointments",{method,headers:{"content-type":"application/json"},body:JSON.stringify(item)}).catch(()=>null);let saved=item;if(response?.ok){const d=await response.json();saved=d.appointment}setAppointments(c=>editing?c.map(a=>a.id===saved.id?saved:a):[...c,saved]);setBookingOpen(false);setEditing(null);flash(editing?"Booking updated.":"Booking created.")}
 async function removeBooking(){if(!selected)return;await fetch(`/api/appointments?id=${selected.id}`,{method:"DELETE"}).catch(()=>null);setAppointments(c=>c.filter(a=>a.id!==selected.id));setSelected(null);flash("Booking deleted.")}
 async function status(s:string){if(!selected)return;await fetch("/api/appointments",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:selected.id,status:s})}).catch(()=>null);setAppointments(c=>c.map(a=>a.id===selected.id?{...a,status:s}:a));setSelected(null);flash(`Booking marked ${s}.`)}
 function edit(a:Appointment){setSelected(null);setEditing(a);setBookingOpen(true)}
 async function addService(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),service:Service={id:Date.now(),name:String(f.get("name")),duration:Number(f.get("duration")),price:Number(f.get("price")),description:String(f.get("description"))};const response=await fetch("/api/services",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(service)}).catch(()=>null);let saved=service;if(response?.ok)saved=(await response.json()).service;setServices(c=>[...c,saved]);setServiceOpen(false);flash("Service added.")}
 async function archive(email:string,restore=false){await fetch("/api/customers",{method:restore?"DELETE":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})}).catch(()=>null);setArchived(c=>restore?c.filter(x=>x!==email):[...new Set([...c,email])]);flash(restore?"Customer restored.":"Customer archived.")}
 async function importIcs(file:File){const text=await file.text(),events=[...text.matchAll(/BEGIN:VEVENT([\s\S]*?)END:VEVENT/g)].map(m=>m[1]),added:Appointment[]=[];for(const block of events){const pick=(key:string)=>block.match(new RegExp(`${key}[^:]*:(.+)`))?.[1]?.trim()??"";const raw=pick("DTSTART"),summary=pick("SUMMARY")||"Google Calendar event",date=raw.slice(0,8),time=raw.slice(9,13);if(date.length===8){added.push({id:Date.now()+added.length,customerName:summary,customerEmail:"",customerPhone:"",service:"Imported event",staffName:"Dimitar",appointmentDate:`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}`,startTime:time.length===4?`${time.slice(0,2)}:${time.slice(2)}`:"09:00",durationMins:60,status:"confirmed",notes:"Imported from Google Calendar",price:0})}}setAppointments(c=>[...c,...added]);flash(`${added.length} Google Calendar event${added.length===1?"":"s"} imported.`)}
 return <main className="pro-shell"><Sidebar view={view} setView={setView}/><section className="pro-main"><header className="pro-header"><div><p>{format(new Date(2026,8,2),"EEEE, MMMM d")}</p><h1>{({overview:"Good morning, Dimitar",calendar:"Calendar",customers:"Customers",services:"Services",settings:"Settings"} as Record<View,string>)[view]}</h1></div><div className="pro-actions"><label><Search/><Input aria-label="Search" placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/></label><Button onClick={()=>{setEditing(null);setBookingOpen(true)}}><Plus/> New booking</Button></div></header>{notice&&<output className="pro-notice">{notice}</output>}
 {view==="overview"&&<Overview appointments={appointments} week={weekAppointments} days={days} weekStart={weekStart} setWeekStart={setWeekStart} select={setSelected}/>} 
 {view==="calendar"&&<MonthView month={month} setMonth={setMonth} appointments={visible} select={setSelected} importIcs={importIcs}/>} 
 {view==="customers"&&<Customers customers={customers} appointments={appointments} archived={archived} archive={archive}/>} 
 {view==="services"&&<Services services={services} appointments={appointments} open={()=>setServiceOpen(true)} book={name=>{setEditing(null);setBookingOpen(true);setTimeout(()=>{const s=document.querySelector<HTMLSelectElement>('select[name="service"]');if(s)s.value=name},0)}}/>}
 {view==="settings"&&<SettingsView/>}</section>
 <BookingDialog open={bookingOpen} setOpen={o=>{setBookingOpen(o);if(!o)setEditing(null)}} submit={saveBooking} services={services} editing={editing}/><ServiceDialog open={serviceOpen} setOpen={setServiceOpen} submit={addService}/><Details selected={selected} setSelected={setSelected} edit={edit} status={status} remove={removeBooking}/></main>}

function Sidebar({view,setView}:{view:View;setView:(v:View)=>void}){const links:[[View,string,React.ReactNode]]|any=[["overview","Overview",<LayoutDashboard key="o"/>],["calendar","Calendar",<CalendarDays key="c"/>],["customers","Customers",<Users key="u"/>],["services","Services",<Clock3 key="s"/>]];return <aside className="pro-sidebar"><div className="pro-logo"><span>A</span><div>Arbor<small>BOOKINGS</small></div></div><nav>{links.map(([v,l,i]:[View,string,React.ReactNode])=><button key={v} className={view===v?"active":""} onClick={()=>setView(v)}>{i}{l}</button>)}</nav><div className="pro-bottom"><button className={view==="settings"?"active":""} onClick={()=>setView("settings")}><Settings/>Settings</button><div className="pro-profile"><b>DS</b><span>Dimitar Shopov<small>Administrator</small></span></div></div></aside>}
function Controls({title,back,next,today}:{title:string;back:()=>void;next:()=>void;today:()=>void}){return <div className="pro-controls"><div><h2>{title}</h2><p>Green: available · Yellow: nearly full · Red: limit reached</p></div><div><Button variant="outline" size="icon" onClick={back}><ChevronLeft/></Button><Button variant="outline" onClick={today}>Today</Button><Button variant="outline" size="icon" onClick={next}><ChevronRight/></Button></div></div>}
function Overview({appointments,week,days,weekStart,setWeekStart,select}:{appointments:Appointment[];week:Appointment[];days:Date[];weekStart:Date;setWeekStart:(d:Date)=>void;select:(a:Appointment)=>void}){const revenue=appointments.filter(a=>a.status!=="cancelled").reduce((s,a)=>s+a.price,0);return <><div className="pro-stats"><article><p>This week</p><strong>{week.length}</strong><span>scheduled bookings</span></article><article><p>Customers</p><strong>{new Set(appointments.map(a=>a.customerEmail||a.customerName)).size}</strong><span>total contacts</span></article><article><p>Expected revenue</p><strong>€{revenue}</strong><span>confirmed work</span></article><article><p>Daily limit</p><strong>{DAILY_LIMIT}</strong><span>bookings per day</span></article></div><section className="pro-card"><Controls title={`${format(days[0],"MMM d")} – ${format(days[6],"MMM d, yyyy")}`} back={()=>setWeekStart(addWeeks(weekStart,-1))} next={()=>setWeekStart(addWeeks(weekStart,1))} today={()=>setWeekStart(startOfWeek(new Date(2026,8,2),{weekStartsOn:1}))}/><Week days={days} appointments={week} select={select}/></section></>}
function Week({days,appointments,select}:{days:Date[];appointments:Appointment[];select:(a:Appointment)=>void}){return <div className="pro-week">{days.map(d=>{const items=appointments.filter(a=>isSameDay(parseISO(a.appointmentDate),d)&&a.status!=="cancelled").sort((a,b)=>a.startTime.localeCompare(b.startTime)),tone=capacity(items.length);return <article key={d.toISOString()}><header><span className={`limit-dot ${tone}`}/><span>{format(d,"EEE")}</span><b>{format(d,"d")}</b><small>{items.length}/{DAILY_LIMIT}</small></header><div>{items.length?items.map(a=><button key={a.id} onClick={()=>select(a)}><time>{a.startTime}</time><b>{a.customerName}</b><small>{a.service}</small></button>):<p>No bookings</p>}</div></article>})}</div>}
function MonthView({month,setMonth,appointments,select,importIcs}:{month:Date;setMonth:(d:Date)=>void;appointments:Appointment[];select:(a:Appointment)=>void;importIcs:(f:File)=>void}){const start=startOfWeek(startOfMonth(month),{weekStartsOn:1}),end=endOfWeek(endOfMonth(month),{weekStartsOn:1}),days=eachDayOfInterval({start,end});return <section className="pro-card"><div className="month-top"><Controls title={format(month,"MMMM yyyy")} back={()=>setMonth(subMonths(month,1))} next={()=>setMonth(addMonths(month,1))} today={()=>setMonth(new Date(2026,8,1))}/><label className="import-button"><Upload/> Import Google Calendar<input type="file" accept=".ics,text/calendar" onChange={e=>e.target.files?.[0]&&importIcs(e.target.files[0])}/></label></div><div className="month-days">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><b key={d}>{d}</b>)}</div><div className="month-grid">{days.map(d=>{const items=appointments.filter(a=>isSameDay(parseISO(a.appointmentDate),d)&&a.status!=="cancelled"),tone=capacity(items.length);return <article className={format(d,"M")!==format(month,"M")?"outside":""} key={d.toISOString()}><header><span>{format(d,"d")}</span><i className={`limit-dot ${tone}`}/><small>{items.length}/{DAILY_LIMIT}</small></header>{items.slice(0,3).map(a=><button key={a.id} onClick={()=>select(a)}><time>{a.startTime}</time>{a.customerName}</button>)}{items.length>3&&<p>+{items.length-3} more</p>}</article>})}</div></section>}
function Customers({customers,appointments,archived,archive}:{customers:Appointment[];appointments:Appointment[];archived:string[];archive:(e:string,r?:boolean)=>void}){const active=customers.filter(c=>!archived.includes(c.customerEmail)),old=customers.filter(c=>archived.includes(c.customerEmail));return <div className="customer-sections"><CustomerList title="Active customers" copy="Customers currently available for bookings." rows={active} appointments={appointments} action={(e)=><Button variant="outline" size="sm" onClick={()=>archive(e)}><Archive/> Archive</Button>}/><CustomerList title="Customer archive" copy="Inactive customers kept for your records." rows={old} appointments={appointments} empty="No archived customers." action={(e)=><Button variant="outline" size="sm" onClick={()=>archive(e,true)}>Restore</Button>}/></div>}
function CustomerList({title,copy,rows,appointments,action,empty}:{title:string;copy:string;rows:Appointment[];appointments:Appointment[];action:(e:string)=>React.ReactNode;empty?:string}){return <section className="pro-card"><div className="section-title"><div><h2>{title}</h2><p>{copy}</p></div><strong>{rows.length}</strong></div><div className="customer-list">{rows.length?rows.map(c=>{const all=appointments.filter(a=>a.customerEmail===c.customerEmail),last=all.sort((a,b)=>b.appointmentDate.localeCompare(a.appointmentDate))[0];return <article key={c.customerEmail}><span className="avatar">{initials(c.customerName)}</span><div><b>{c.customerName}</b><small>{c.customerEmail} · {c.customerPhone||"No phone"}</small></div><div><span>{all.length} bookings</span><small>Last: {format(parseISO(last.appointmentDate),"MMM d, yyyy")}</small></div><span className={`customer-state ${last.status}`}>{last.status}</span>{action(c.customerEmail)}</article>}):<p className="empty">{empty||"No customers found."}</p>}</div></section>}
function Services({services,appointments,open,book}:{services:Service[];appointments:Appointment[];open:()=>void;book:(n:string)=>void}){return <><div className="section-action"><div><h2>Services</h2><p>Manage the appointments your business offers.</p></div><Button onClick={open}><Plus/> Add service</Button></div><div className="service-cards">{services.map(s=><article key={s.id}><Clock3/><h2>{s.name}</h2><p>{s.description}</p><div><span>{s.duration} min</span><strong>€{s.price}</strong></div><small>{appointments.filter(a=>a.service===s.name).length} bookings</small><Button variant="outline" onClick={()=>book(s.name)}>Book service</Button></article>)}</div></>}
function BookingDialog({open,setOpen,submit,services,editing}:{open:boolean;setOpen:(o:boolean)=>void;submit:(e:FormEvent<HTMLFormElement>)=>void;services:Service[];editing:Appointment|null}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="booking-dialog"><DialogHeader><DialogTitle>{editing?"Edit booking":"New booking"}</DialogTitle><DialogDescription>{editing?"Update the appointment details below.":"Add an appointment. Conflicting times are blocked."}</DialogDescription></DialogHeader><form key={editing?.id??"new"} onSubmit={submit} className="booking-form"><label>Customer name<Input name="customerName" defaultValue={editing?.customerName} required/></label><div className="form-row"><label>Email<Input name="customerEmail" type="email" defaultValue={editing?.customerEmail} required/></label><label>Phone<Input name="customerPhone" defaultValue={editing?.customerPhone}/></label></div><div className="form-row"><label>Service<select name="service" defaultValue={editing?.service??services[0]?.name}>{services.map(s=><option key={s.id}>{s.name}</option>)}</select></label><label>Team member<select name="staffName" defaultValue={editing?.staffName??"Dimitar"}><option>Dimitar</option><option>Elena</option></select></label></div><div className="form-row three"><label>Date<Input name="appointmentDate" type="date" defaultValue={editing?.appointmentDate??"2026-09-03"} required/></label><label>Start<Input name="startTime" type="time" defaultValue={editing?.startTime??"11:00"} required/></label><label>Duration<select name="durationMins" defaultValue={editing?.durationMins??60}><option value="30">30 min</option><option value="45">45 min</option><option value="60">60 min</option><option value="90">90 min</option></select></label></div><label>Price (€)<Input name="price" type="number" min="0" defaultValue={editing?.price??75}/></label><label>Notes<Textarea name="notes" defaultValue={editing?.notes}/></label><Button type="submit">{editing?"Save changes":"Create booking"}</Button></form></DialogContent></Dialog>}
function ServiceDialog({open,setOpen,submit}:{open:boolean;setOpen:(o:boolean)=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <Dialog open={open} onOpenChange={setOpen}><DialogContent className="small-dialog"><DialogHeader><DialogTitle>Add service</DialogTitle><DialogDescription>Create a service customers can book.</DialogDescription></DialogHeader><form onSubmit={submit} className="booking-form"><label>Name<Input name="name" required/></label><div className="form-row"><label>Duration<Input name="duration" type="number" min="15" defaultValue="60"/></label><label>Price (€)<Input name="price" type="number" min="0" defaultValue="50"/></label></div><label>Description<Textarea name="description" required/></label><Button type="submit">Add service</Button></form></DialogContent></Dialog>}
function Details({selected,setSelected,edit,status,remove}:{selected:Appointment|null;setSelected:(a:Appointment|null)=>void;edit:(a:Appointment)=>void;status:(s:string)=>void;remove:()=>void}){return <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="details-dialog"><DialogHeader><DialogTitle>{selected?.customerName}</DialogTitle><DialogDescription>{selected?.service} with {selected?.staffName}</DialogDescription></DialogHeader>{selected&&<div className="details"><p><span>Date</span><b>{format(parseISO(selected.appointmentDate),"EEEE, MMMM d")}</b></p><p><span>Time</span><b>{selected.startTime} · {selected.durationMins} min</b></p><p><span>Status</span><b>{selected.status}</b></p><p><span>Contact</span><b>{selected.customerEmail||selected.customerPhone}</b></p><p><span>Notes</span><b>{selected.notes||"No notes"}</b></p><div className="detail-actions"><Button onClick={()=>edit(selected)}>Edit</Button><Button variant="outline" onClick={()=>status("completed")}>Complete</Button><Button variant="outline" className="danger" onClick={remove}><Trash2/> Delete</Button></div></div>}</DialogContent></Dialog>}
function SettingsView(){return <section className="pro-card settings"><div className="section-title"><div><h2>Business settings</h2><p>Capacity indicators use a daily limit of {DAILY_LIMIT} bookings.</p></div></div><label>Business name<Input defaultValue="Arbor Bookings"/></label><label>Working hours<div><Input type="time" defaultValue="09:00"/><span>to</span><Input type="time" defaultValue="17:00"/></div></label><Button>Save settings</Button></section>}
function capacity(n:number){return n>=DAILY_LIMIT?"red":n>=DAILY_LIMIT-2?"yellow":"green"}function mins(v:string){const[h,m]=v.split(":").map(Number);return h*60+m}function initials(n:string){return n.split(" ").map(x=>x[0]).join("").slice(0,2)}
