"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, LayoutDashboard, Search, Settings, Sparkles, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

type Appointment={id:number;customerName:string;customerEmail:string;customerPhone:string;service:string;staffName:string;appointmentDate:string;startTime:string;durationMins:number;status:string;notes:string;price:number;tone:string};
const samples:Appointment[]=[
  {id:-1,customerName:"Maya Chen",customerEmail:"maya@example.com",customerPhone:"",service:"Consultation",staffName:"Dimitar",appointmentDate:"2026-09-01",startTime:"09:30",durationMins:60,status:"confirmed",notes:"First consultation",price:75,tone:"sage"},
  {id:-2,customerName:"Daniel Reed",customerEmail:"daniel@example.com",customerPhone:"",service:"Follow-up",staffName:"Dimitar",appointmentDate:"2026-09-02",startTime:"10:30",durationMins:45,status:"confirmed",notes:"Review progress",price:45,tone:"blue"},
  {id:-3,customerName:"Sofia Patel",customerEmail:"sofia@example.com",customerPhone:"",service:"Strategy session",staffName:"Elena",appointmentDate:"2026-09-04",startTime:"10:00",durationMins:90,status:"confirmed",notes:"Quarterly planning",price:120,tone:"rose"},
  {id:-4,customerName:"Lucas Martin",customerEmail:"lucas@example.com",customerPhone:"",service:"Quick check-in",staffName:"Dimitar",appointmentDate:"2026-09-01",startTime:"12:00",durationMins:30,status:"completed",notes:"",price:30,tone:"sand"},
  {id:-5,customerName:"Amelia Stone",customerEmail:"amelia@example.com",customerPhone:"",service:"Consultation",staffName:"Elena",appointmentDate:"2026-09-03",startTime:"13:00",durationMins:60,status:"confirmed",notes:"",price:75,tone:"blue"},
  {id:-6,customerName:"Noah Wilson",customerEmail:"noah@example.com",customerPhone:"",service:"Follow-up",staffName:"Dimitar",appointmentDate:"2026-09-05",startTime:"12:30",durationMins:45,status:"confirmed",notes:"",price:45,tone:"sage"},
];
const days=["2026-09-01","2026-09-02","2026-09-03","2026-09-04","2026-09-05"];
const dayLabels=["TUE 1","WED 2","THU 3","FRI 4","SAT 5"];

export default function BookingBoard(){
  const [appointments,setAppointments]=useState(samples),[newOpen,setNewOpen]=useState(false),[selected,setSelected]=useState<Appointment|null>(null),[query,setQuery]=useState(""),[searchOpen,setSearchOpen]=useState(false),[notice,setNotice]=useState("");
  const appointmentsRef=useRef(appointments);appointmentsRef.current=appointments;
  useEffect(()=>{fetch("/api/appointments").then(r=>r.ok?r.json():null).then(data=>{if(data?.appointments?.length)setAppointments(data.appointments.map((a:Appointment,i:number)=>({...a,tone:["sage","blue","rose","sand"][i%4]})));}).catch(()=>{});},[]);
  async function createBooking(payload:Omit<Appointment,"id"|"tone"|"status">){
    const start=minutes(payload.startTime),end=start+payload.durationMins;const conflict=appointmentsRef.current.some(a=>a.status!=="cancelled"&&a.appointmentDate===payload.appointmentDate&&a.staffName===payload.staffName&&start<minutes(a.startTime)+a.durationMins&&end>minutes(a.startTime));if(conflict)throw new Error(`${payload.staffName} already has a booking during that time.`);
    const draft:Appointment={...payload,id:Date.now(),status:"confirmed",tone:["sage","blue","rose","sand"][appointmentsRef.current.length%4]};
    const response=await fetch("/api/appointments",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}).catch(()=>null);if(response?.ok){const data=await response.json();draft.id=data.appointment.id;}
    setAppointments(current=>[...current,draft]);setNotice("Booking created successfully.");setTimeout(()=>setNotice(""),3000);return draft;
  }
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await createBooking({customerName:String(form.get("customerName")),customerEmail:String(form.get("customerEmail")),customerPhone:String(form.get("customerPhone")),service:String(form.get("service")),staffName:String(form.get("staffName")),appointmentDate:String(form.get("appointmentDate")),startTime:String(form.get("startTime")),durationMins:Number(form.get("durationMins")),notes:String(form.get("notes")),price:Number(form.get("price"))});setNewOpen(false);}catch(error){setNotice(error instanceof Error?error.message:"Could not create booking.");}}
  async function updateStatus(status:string){if(!selected)return;setAppointments(current=>current.map(a=>a.id===selected.id?{...a,status}:a));if(selected.id>0)await fetch("/api/appointments",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:selected.id,status})}).catch(()=>null);setSelected(null);setNotice(`Booking marked ${status}.`);setTimeout(()=>setNotice(""),3000);}
  useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"create_appointment",title:"Create appointment",description:"Create a new appointment on the visible Arbor booking board after validating staff availability.",inputSchema:{type:"object",properties:{customerName:{type:"string"},customerEmail:{type:"string"},customerPhone:{type:"string"},service:{type:"string"},staffName:{type:"string"},appointmentDate:{type:"string",description:"YYYY-MM-DD"},startTime:{type:"string",description:"HH:MM"},durationMins:{type:"integer",minimum:15,maximum:240},notes:{type:"string"},price:{type:"number"}},required:["customerName","service","staffName","appointmentDate","startTime","durationMins"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const item=await createBooking(input as Omit<Appointment,"id"|"tone"|"status">);return{id:item.id,status:item.status,customerName:item.customerName,startTime:item.startTime};}},{signal:lifecycle.signal})).catch(()=>{});void Promise.resolve(context.registerTool({name:"list_appointments",title:"List appointments",description:"Return the appointments currently visible on the Arbor booking board.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({appointments:appointmentsRef.current.map(({id,customerName,service,appointmentDate,startTime,status})=>({id,customerName,service,appointmentDate,startTime,status}))})},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
  const visible=appointments.filter(a=>(a.customerName+" "+a.service).toLowerCase().includes(query.toLowerCase()));const today=appointments.filter(a=>a.appointmentDate==="2026-09-02"&&a.status!=="cancelled"),revenue=appointments.filter(a=>a.status!=="cancelled").reduce((sum,a)=>sum+a.price,0);
  return <main className="app-shell">
    <aside className="sidebar"><div className="logo"><span>A</span><div>Arbor<small>BOOKINGS</small></div></div><nav><a className="active"><LayoutDashboard/>Overview</a><a><CalendarDays/>Calendar</a><a><Users/>Customers</a><a><Clock3/>Services</a></nav><div className="sidebar-bottom"><a><Settings/>Settings</a><div className="profile"><div>DS</div><span>Dimitar Shopov<small>Administrator</small></span></div></div></aside>
    <section className="workspace"><header><div><p>Wednesday, September 2</p><h1>Good morning, Dimitar</h1></div><div className="header-actions">{searchOpen?<Input className="search-input" autoFocus placeholder="Search bookings…" value={query} onChange={e=>setQuery(e.target.value)}/>:<button className="search" onClick={()=>setSearchOpen(true)}><Search/> Search</button>}<button className="new-booking" onClick={()=>setNewOpen(true)}><Sparkles/> New booking</button></div></header>
    {notice&&<div className="notice" role="status">{notice}</div>}<div className="stats"><article><p>Today’s bookings</p><strong>{today.length}</strong><span>{today.filter(a=>a.startTime>"11:35").length} remaining</span></article><article><p>This week</p><strong>{appointments.length}</strong><span className="positive">↑ 12% from last week</span></article><article><p>Expected revenue</p><strong>€{revenue.toLocaleString()}</strong><span>Across {appointments.length} bookings</span></article><article><p>Open slots</p><strong>11</strong><span>Next: today at 15:30</span></article></div>
    <section className="calendar-card"><div className="calendar-head"><div><h2>September 1–5</h2><p>{visible.length} appointments · weekly schedule</p></div><div><button><ChevronLeft/></button><button className="today">Today</button><button><ChevronRight/></button></div></div><div className="week-grid"><div className="corner">GMT+3</div>{dayLabels.map((d,i)=><div className={i===1?"day today-col":"day"} key={d}><span>{d.split(" ")[0]}</span><b>{d.split(" ")[1]}</b></div>)}{["09:00","10:00","11:00","12:00","13:00","14:00","15:00","16:00"].map(t=><div className="time" key={t}>{t}</div>)}<div className="grid-lines">{Array.from({length:40}).map((_,i)=><i key={i}/>)}</div>{visible.map(a=>{const day=days.indexOf(a.appointmentDate);if(day<0)return null;const slot=(minutes(a.startTime)-540)/30;return <button className={`appointment ${a.tone} ${a.status}`} key={a.id} style={{gridColumn:day+2,gridRow:`${Math.floor(slot)+2} / span ${Math.max(1,Math.ceil(a.durationMins/30))}`}} onClick={()=>setSelected(a)}><span>{a.startTime}</span><b>{a.customerName}</b><small>{a.service}</small></button>})}<div className="now-line"><span>11:35</span></div></div></section></section>
    <aside className="day-panel"><div className="day-title"><span>Wednesday</span><strong>02</strong></div><div className="next-label"><span>UP NEXT</span><b>{today.length} appointments</b></div><div className="agenda">{today.map(a=><button key={a.id} onClick={()=>setSelected(a)}><i className={a.tone}/><time>{a.startTime}</time><div><b>{a.customerName}</b><span>{a.service} · {a.durationMins} min</span></div></button>)}</div><div className="availability-card"><span>AVAILABLE TODAY</span><strong>2h 15m</strong><p>Three open time slots remain.</p><button onClick={()=>setNewOpen(true)}>Book a time →</button></div></aside>
    <Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent className="booking-dialog"><DialogHeader><DialogTitle>New booking</DialogTitle><DialogDescription>Add a customer appointment. Conflicting times are blocked automatically.</DialogDescription></DialogHeader><form onSubmit={submit} className="booking-form"><label>Customer name<Input name="customerName" required placeholder="Full name"/></label><div className="form-row"><label>Email<Input name="customerEmail" type="email" placeholder="customer@email.com"/></label><label>Phone<Input name="customerPhone" placeholder="+359…"/></label></div><div className="form-row"><label>Service<select name="service" defaultValue="Consultation"><option>Consultation</option><option>Follow-up</option><option>Strategy session</option><option>Quick check-in</option></select></label><label>Team member<select name="staffName" defaultValue="Dimitar"><option>Dimitar</option><option>Elena</option></select></label></div><div className="form-row three"><label>Date<Input name="appointmentDate" type="date" defaultValue="2026-09-03" required/></label><label>Start<Input name="startTime" type="time" defaultValue="11:00" required/></label><label>Duration<select name="durationMins" defaultValue="60"><option value="30">30 min</option><option value="45">45 min</option><option value="60">60 min</option><option value="90">90 min</option></select></label></div><label>Price (€)<Input name="price" type="number" min="0" defaultValue="75"/></label><label>Notes<Textarea name="notes" placeholder="Anything the team should know…"/></label><Button type="submit" className="save-booking">Create booking</Button></form></DialogContent></Dialog>
    <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="details-dialog"><DialogHeader><DialogTitle>{selected?.customerName}</DialogTitle><DialogDescription>{selected?.service} with {selected?.staffName}</DialogDescription></DialogHeader>{selected&&<div className="details"><p><span>Date</span><b>{selected.appointmentDate}</b></p><p><span>Time</span><b>{selected.startTime} · {selected.durationMins} min</b></p><p><span>Status</span><b className={`status ${selected.status}`}>{selected.status}</b></p><p><span>Contact</span><b>{selected.customerEmail||selected.customerPhone||"Not provided"}</b></p><p><span>Notes</span><b>{selected.notes||"No notes"}</b></p><div className="status-actions"><Button onClick={()=>updateStatus("completed")}>Mark completed</Button><Button variant="outline" onClick={()=>updateStatus("cancelled")}>Cancel booking</Button></div></div>}</DialogContent></Dialog>
  </main>;
}
function minutes(value:string){const [h,m]=value.split(":").map(Number);return h*60+m;}
